SELECT * FROM TB_SEADE_CODIGOS_DOS_MUNICIPIOS_IBGE WHERE CIDADES = 'Santana de Parnaíba';

CREATE TABLE TB_SEADE_CODIGOS_DOS_MUNICIPIOS_IBGE(
COD_IBGE INT primary KEY,
CIDADES VARCHAR(100),
COD_RA VARCHAR(24) ,
REG_ADMINISTRATIVA	VARCHAR(100),
REG_METROPOLITANAS	VARCHAR(100),
COD_IBGE6	INT,
POP_2020 VARCHAR(24),
PORTE_POP2020 VARCHAR(100),	
COD_DRS	VARCHAR(24) ,
DRS VARCHAR(100)
);

CREATE TABLE TB_SEADE_obitosinfantis_periodo(
COD_IBGE INT NOT NULL,
ANO INT,
OB_MENORES_1ANO INT,
OB_MENORES_7DIAS INT,
OB_28DIAS_A_364DIAS INT,
OB_7_A_27DIAS INT,
NASCIDOS_VIVOS INT,
FOREIGN KEY (COD_IBGE) REFERENCES TB_SEADE_CODIGOS_DOS_MUNICIPIOS_IBGE(COD_IBGE)
)

CREATE TABLE TB_SEADE_obitosinfantis_principais_causas(
COD_IBGE INT NOT NULL,
ANO INT,
NASCIDOS_VIVOS INT,
PERINATAIS INT,
MALFORMACAO_CONGENITA INT,
DOENCAS_AP_RESPIRATORIO INT,
INFECSIOSAS_E_PARASITARIAS INT,
FOREIGN KEY (COD_IBGE) REFERENCES TB_SEADE_CODIGOS_DOS_MUNICIPIOS_IBGE(COD_IBGE)
)

CREATE TABLE TB_SEADE_saude_leitos_mun_ano (
COD_IBGE INT NOT NULL,
CIDADE VARCHAR(100),
ANO INT,
LEITOS_TOTAL INT,
LEITOS_POR_HAB FLOAT,
LEITOS_SUS INT,
LEITOS_SUS_POR_HAB FLOAT,
LEITOS_NAO_SUS INT,
LEITOS_NAO_SUS_POR_HAB FLOAT,
FOREIGN KEY (COD_IBGE) REFERENCES TB_SEADE_CODIGOS_DOS_MUNICIPIOS_IBGE(COD_IBGE)
);

CREATE TABLE TB_SEADE_saude_med_enf_mun_ano(
COD_IBGE INT NOT NULL,
MUNICIPIO VARCHAR(100),	
PROF_SUS INT,
PROF_N_SUS	INT,
PROF_TOTAL	INT,
CLASSE VARCHAR(100),		
PROF_POR_HABITANTE FLOAT,
FOREIGN KEY (COD_IBGE) REFERENCES TB_SEADE_CODIGOS_DOS_MUNICIPIOS_IBGE(COD_IBGE)
);

CREATE TABLE TB_SEADE_obitos_sexo_idade_anoatual (
COD_IBGE  INT NOT NULL,
ANO INT,
SEXO VARCHAR(8),
IDADE VARCHAR(14),
OBITO INT,
FOREIGN KEY (COD_IBGE) REFERENCES TB_SEADE_CODIGOS_DOS_MUNICIPIOS_IBGE(COD_IBGE)
);

CREATE TABLE TB_SEADE_obitos_sexo_idade_periodo (
COD_IBGE  INT NOT NULL,
ANO INT,
SEXO VARCHAR(8),
IDADE VARCHAR(14),
OBITO INT,
FOREIGN KEY (COD_IBGE) REFERENCES TB_SEADE_CODIGOS_DOS_MUNICIPIOS_IBGE(COD_IBGE)
);

CREATE TABLE TB_SEADE_nascidosvivos_sexo_populacao_2021(
COD_IBGE INT NOT NULL,
ANO INT,
CIDADE VARCHAR(100),
MASCULINO INT,
FEMININO INT,
IGNORADO INT,
NASCIDOS_VIVOS INT,
POPULACAO_2021 INT,
FOREIGN KEY (COD_IBGE) REFERENCES TB_SEADE_CODIGOS_DOS_MUNICIPIOS_IBGE(COD_IBGE)
);

CREATE TABLE TB_SEADE_obitos_esp_mes_ocorrencia_area_periodo (
COD_IBGE  INT NOT NULL,
ANO INT,	
MES VARCHAR (9),
OBITOS INT,
FOREIGN KEY (COD_IBGE) REFERENCES TB_SEADE_CODIGOS_DOS_MUNICIPIOS_IBGE(COD_IBGE)
);

CREATE TABLE TB_SEADE_obitos_gerais_2000a2021(
COD_IBGE  INT NOT NULL,
CIDADE VARCHAR (100),
ANO INT ,
OBITOS_GERAIS	INT,
FOREIGN KEY (COD_IBGE) REFERENCES TB_SEADE_CODIGOS_DOS_MUNICIPIOS_IBGE(COD_IBGE)
);

CREATE TABLE TB_SEADE_obitos_mes_anoatual (
COD_IBGE  INT NOT NULL,
ANO INT,	
MES VARCHAR (9),
OBITOS INT,
FOREIGN KEY (COD_IBGE) REFERENCES TB_SEADE_CODIGOS_DOS_MUNICIPIOS_IBGE(COD_IBGE)
);

CREATE TABLE TB_SEADE_obitos_mes_anoatual (
COD_IBGE  INT NOT NULL,
ANO INT,	
MES VARCHAR (9),
OBITOS INT,
FOREIGN KEY (COD_IBGE) REFERENCES TB_SEADE_CODIGOS_DOS_MUNICIPIOS_IBGE(COD_IBGE)
);

CREATE TABLE TB_SEADE_nascidosvivos_mesocorrencia_2019a2021(
COD_IBGE INT NOT NULL,
ANO INT,
MES VARCHAR (9),
NASCIDOS_VIVOS INT,
FOREIGN KEY (COD_IBGE) REFERENCES TB_SEADE_CODIGOS_DOS_MUNICIPIOS_IBGE(COD_IBGE)
);

CREATE TABLE TB_SEADE_nascidosvivos_mesocorrencia_2020a2022(
COD_IBGE INT NOT NULL,
ANO INT,
MES VARCHAR (9),
NASCIDOS_VIVOS INT,
FOREIGN KEY (COD_IBGE) REFERENCES TB_SEADE_CODIGOS_DOS_MUNICIPIOS_IBGE(COD_IBGE)
);

CREATE TABLE TB_SEADE_nascidosvivos_mesocorrencia_2021a2023(
COD_IBGE INT NOT NULL,
ANO INT,
MES VARCHAR (9),
NASCIDOS_VIVOS INT,
FOREIGN KEY (COD_IBGE) REFERENCES TB_SEADE_CODIGOS_DOS_MUNICIPIOS_IBGE(COD_IBGE)
);

CREATE TABLE TB_SEADE_nascidosvivos_sexo_2022(
COD_IBGE INT NOT NULL,
ANO INT,
CIDADE VARCHAR(100),
MASCULINO INT,
FEMININO INT,
IGNORADO INT,
NASCIDOS_VIVOS INT,
FOREIGN KEY (COD_IBGE) REFERENCES TB_SEADE_CODIGOS_DOS_MUNICIPIOS_IBGE(COD_IBGE)
);

CREATE TABLE TB_SEADE_nascidosvivos_sexo_2023(
COD_IBGE INT NOT NULL,
ANO INT,
CIDADE VARCHAR(100),
MASCULINO INT,
FEMININO INT,
IGNORADO INT,
NASCIDOS_VIVOS INT,
FOREIGN KEY (COD_IBGE) REFERENCES TB_SEADE_CODIGOS_DOS_MUNICIPIOS_IBGE(COD_IBGE)
);

CREATE TABLE TB_SEADE_nascidosvivos_sexo_anoatual(
COD_IBGE INT NOT NULL,
ANO INT,
MASCULINO INT,
FEMININO INT,
NASCIDOS_VIVOS INT,
FOREIGN KEY (COD_IBGE) REFERENCES TB_SEADE_CODIGOS_DOS_MUNICIPIOS_IBGE(COD_IBGE)
);

CREATE TABLE TB_SEADE_nascidosvivos_2000a2023(
COD_IBGE INT NOT NULL,
ANO INT,
NASCIDOS_VIVOS INT,
FOREIGN KEY (COD_IBGE) REFERENCES TB_SEADE_CODIGOS_DOS_MUNICIPIOS_IBGE(COD_IBGE)
);

CREATE TABLE TB_SEADE_nascidosvivos_idade_2000_2010_2021(
COD_IBGE INT NOT NULL,
ANO INT,
IDADE VARCHAR(8),
NASCIDOSVIVOS_IDADE  INT,
NASCIDOS_VIVOS  INT,
FOREIGN KEY (COD_IBGE) REFERENCES TB_SEADE_CODIGOS_DOS_MUNICIPIOS_IBGE(COD_IBGE)
);

CREATE TABLE TB_SEADE_nascidosvivos_idade_2000_2010_2023(
COD_IBGE INT NOT NULL,
ANO INT,
IDADE VARCHAR(8),
NASCIDOSVIVOS_IDADE  INT,
NASCIDOS_VIVOS  INT,
FOREIGN KEY (COD_IBGE) REFERENCES TB_SEADE_CODIGOS_DOS_MUNICIPIOS_IBGE(COD_IBGE)
);

CREATE TABLE TB_SEADE_nascidosvivos_idade_anoatual (
COD_IBGE INT NOT NULL,
ANO INT,
IDADE VARCHAR(8),
NASCIDOS_VIVOS  INT,
FOREIGN KEY (COD_IBGE) REFERENCES TB_SEADE_CODIGOS_DOS_MUNICIPIOS_IBGE(COD_IBGE)
);

CREATE TABLE TB_SEADE_econ_vti(
COD_MUNICIPIO INT NOT NULL,
CIDADE  VARCHAR(100),
ANO INT ,
DESCRICAO_SETOR VARCHAR(61),
VTI_EM_REAIS_CORRENTES DOUBLE,
FOREIGN KEY (COD_MUNICIPIO) REFERENCES TB_SEADE_CODIGOS_DOS_MUNICIPIOS_IBGE(COD_IBGE)
);

CREATE TABLE TB_SEADE_evolucao_casamentos(
COD_IBGE INT NOT NULL,
ANO  INT ,
ENTRE_PESSOAS_DE_SEXOS_DIFERENTES  INT ,
ENTRE_PESSOAS_DO_MESMO_SEXO INT ,
IGNORADO  INT ,
TOTAL INT ,
FOREIGN KEY (COD_IBGE) REFERENCES TB_SEADE_CODIGOS_DOS_MUNICIPIOS_IBGE(COD_IBGE)
);

CREATE TABLE TB_SEADE_fecundidade_natalidade_municipios_serie(
COD_IBGE INT NOT NULL,
ANO INT ,
NASCIDOS_VIVOS INT ,
POPFEM_15A49ANOS INT ,
POPULACAO INT ,
FOREIGN KEY (COD_IBGE) REFERENCES TB_SEADE_CODIGOS_DOS_MUNICIPIOS_IBGE(COD_IBGE)
);

CREATE TABLE TB_SEADE_fecund_natale_variacoesperiodos_municipios(
COD_IBGE INT NOT NULL,
NASCIDOS_VIVOS_2000 INT ,
POPFEM_15A49ANOS_2000 INT ,
POPULACAO_2000 INT ,
NASCIDOS_VIVOS_2010 INT ,
POPFEM_15A49ANOS_2010 INT ,
POPULACAO_2010 INT ,
NASCIDOS_VIVOS_2022 INT ,
POPFEM_15A49ANOS_2022 INT ,
POPULACAO_2022 INT ,
FOREIGN KEY (COD_IBGE) REFERENCES TB_SEADE_CODIGOS_DOS_MUNICIPIOS_IBGE(COD_IBGE)
);

CREATE TABLE TB_SEADE_inpc_1995_2019(
VARIACAO_ACUMULADA_NO_ANO_DURANTE_O_PLANOREAL INT,	
BRASIL FLOAT,
FATOR_CORRECAO_2012_2018 FLOAT
);

CREATE TABLE TB_SEADE_medicos_tipos(
COD_IBGE INT NOT NULL,
TIPO INT ,
SUS INT ,
NAO_SUS INT ,
TOTAL INT ,
FOREIGN KEY (COD_IBGE) REFERENCES TB_SEADE_CODIGOS_DOS_MUNICIPIOS_IBGE(COD_IBGE)
);

CREATE TABLE TB_SEADE_casamentos_mes_periodo(
COD_IBGE INT NOT NULL,
ANO INT ,
MES INT ,
CASAMENTOS INT ,
FOREIGN KEY (COD_IBGE) REFERENCES TB_SEADE_CODIGOS_DOS_MUNICIPIOS_IBGE(COD_IBGE)
);

CREATE TABLE TB_SEADE_divisoes_regionais_esp(
COD_IBGE  INT NOT NULL,
CIDADE VARCHAR(100),
COD_RA INT,
REGIAO_ADMINISTRATIVA VARCHAR(50),
REGIAO_METROPOLITANA VARCHAR(50),
COD_IBGE_6DIGITOS INT,
POPULACAO_2020 INT,
PORTE_POPULACAO_2020 VARCHAR(30),
LATITUDE DOUBLE,
LONGITUDE DOUBLE,
FOREIGN KEY (COD_IBGE) REFERENCES TB_SEADE_CODIGOS_DOS_MUNICIPIOS_IBGE(COD_IBGE)
);

CREATE TABLE TB_SEADE_econ_comex(
COD_IBGE  INT NOT NULL,
CIDADE VARCHAR(100),
VALOR_EXPORTACOES_US_FOB REAL,
VALOR_IMPORTACOES_US_FOB REAL,
FOREIGN KEY (COD_IBGE) REFERENCES TB_SEADE_CODIGOS_DOS_MUNICIPIOS_IBGE(COD_IBGE)
);

CREATE TABLE TB_SEADE_econ_pib(
COD_IBGE INT NOT NULL,
CIDADE VARCHAR(100),
SETOR  VARCHAR(40),
ANO INT,
VALOR REAL,
FOREIGN KEY (COD_IBGE) REFERENCES TB_SEADE_CODIGOS_DOS_MUNICIPIOS_IBGE(COD_IBGE)
);

CREATE TABLE TB_SEADE_cas_sexo_idade_conjuges_periodo(
COD_IBGE INT NOT NULL,
ANO INT,
CASAMENTOS VARCHAR(35),
SEXO VARCHAR(8),
IDADE VARCHAR(8),
CONJUGES INT,
FOREIGN KEY (COD_IBGE) REFERENCES TB_SEADE_CODIGOS_DOS_MUNICIPIOS_IBGE(COD_IBGE)
);

CREATE TABLE TB_SEADE_casamento_mes_anoatual(
COD_IBGE  INT NOT NULL,
ANO INT,
MES_CASAMENTO INT,
CASAMENTOS INT,
FOREIGN KEY (COD_IBGE) REFERENCES TB_SEADE_CODIGOS_DOS_MUNICIPIOS_IBGE(COD_IBGE)
);

CREATE TABLE TB_SEADE_casamentos_ano_2021(
COD_IBGE INT NOT NULL,
ANO INT,
SEXO_DIFERENTE INT,
MESMO_SEXO INT,
TOTAL INT,
FOREIGN KEY (COD_IBGE) REFERENCES TB_SEADE_CODIGOS_DOS_MUNICIPIOS_IBGE(COD_IBGE)
);

CREATE TABLE TB_SEADE_casamentos_ano_2022(
COD_IBGE INT NOT NULL,
ANO INT,
SEXO_DIFERENTE INT,
MESMO_SEXO INT,
IGNORADO INT,
TOTAL INT,
FOREIGN KEY (COD_IBGE) REFERENCES TB_SEADE_CODIGOS_DOS_MUNICIPIOS_IBGE(COD_IBGE)
);

CREATE TABLE TB_SEADE_casamentos_ano_2023(
COD_IBGE INT NOT NULL,
ANO INT,
SEXO_DIFERENTE INT,
MESMO_SEXO INT,
IGNORADO INT,
TOTAL INT,
FOREIGN KEY (COD_IBGE) REFERENCES TB_SEADE_CODIGOS_DOS_MUNICIPIOS_IBGE(COD_IBGE)
);

CREATE TABLE TB_SEADE_casamentos_anoatual(
COD_IBGE INT NOT NULL,
ANO INT,
SEXO_DIFERENTE INT,
MESMO_SEXO INT,
IGNORADO INT,
TOTAL INT,
FOREIGN KEY (COD_IBGE) REFERENCES TB_SEADE_CODIGOS_DOS_MUNICIPIOS_IBGE(COD_IBGE)
);

CREATE TABLE TB_SEADE_cas_sexo_idade_anoatual(
COD_IBGE INT NOT NULL,
ANO INT,
HOMOAFETIVO varchar(5),
SEXO char(1),
FAIXA_ETARIA varchar(15),
CASAMENTOS int,
FOREIGN KEY (COD_IBGE) REFERENCES TB_SEADE_CODIGOS_DOS_MUNICIPIOS_IBGE(COD_IBGE)
);

CREATE TABLE TB_SEADE_mortalidade_geral(
COD_IBGE  INT NOT NULL,
CIDADE	VARCHAR(100),
ANO	INT,
OBITOS_0A14	 INT,
OBITOS_15A29 INT,
OBITOS_30A44 INT,
OBITOS_45A59 INT,	
OBITOS_60E INT,
OBITOS_IGNORADO	 INT,
OBITOS_TOTAL INT,
POP_0A14 INT,
POP_15A29 INT,
POP_30A44 INT,
POP_45A59 INT,
POP_60E INT,
POP_TOTAL INT,
MX_0A14	FLOAT,
MX_15A29 FLOAT,
MX_30A44 FLOAT,
MX_45A59 FLOAT,
MX_60E FLOAT,
MX_TOTAL FLOAT,
FOREIGN KEY (COD_IBGE) REFERENCES TB_SEADE_CODIGOS_DOS_MUNICIPIOS_IBGE(COD_IBGE)
);

