CREATE TABLE TB_Censo2022_PiramideEtaria (
GRUPO_DE_IDADE VARCHAR(16),
POPULACAO_FEMININA INT,
POPULACAO_MASCULINA	INT,
MUNICIPIO VARCHAR(20),
SIGLA_UF VARCHAR(2),
CODIGO_DO_MUNICIPIO INT
)


CREATE TABLE TB_Censo2022_PopulacaoPorCorOuRaca(
COR_OU_RAÇA VARCHAR (8),
POPULACAO INT,
MUNICIPIO VARCHAR(20),
SIGLA_UF VARCHAR(2),
CODIGO_DO_MUNICIPIO INT
);


CREATE TABLE TB_Censo2022_PopulacaoPorSexo (
SEXO VARCHAR (8),
POPULACAO INT,
MUNICIPIO VARCHAR(20),
SIGLA_UF VARCHAR(2),
CODIGO_DO_MUNICIPIO INT
);

CREATE TABLE TB_Censo2022_Territorio(
ANO_DA_PESQUISA INT,
AREA_KM2 FLOAT,
DENSIDADE_DEMOGRAFICA FLOAT,
MUNICIPIO VARCHAR(20),
SIGLA_UF VARCHAR(2),
CODIGO_DO_MUNICIPIO INT
);

CREATE TABLE TB_Censo2022_CaracteristicasDosDomicilios(
CARACTERISTICA VARCHAR (40),
NAO_POSSUI FLOAT,
POSSUI FLOAT, 
MUNICIPIO VARCHAR(20),
SIGLA_UF VARCHAR(2),
CODIGO_DO_MUNICIPIO INT
);


CREATE TABLE TB_Censo2022_CrescimentoPopulacional (
ANO_DA_PESQUISA INT,
POPULACAO INT,
MUNICIPIO VARCHAR(20),
SIGLA_UF VARCHAR(2),
CODIGO_DO_MUNICIPIO INT
);


